CREATE TABLE oauth2_authorization
(
    `id`                            varchar(100) NOT NULL,
    `registered_client_id`          varchar(100) NOT NULL,
    `principal_name`                varchar(200) NOT NULL,
    `authorization_grant_type`      varchar(100) NOT NULL,
    `authorized_scopes`             varchar(1000) DEFAULT NULL,
    `attributes`                    blob,
    `state`                         varchar(500)  DEFAULT NULL,
    `authorization_code_value`      blob,
    `authorization_code_issued_at`  timestamp NULL DEFAULT NULL,
    `authorization_code_expires_at` timestamp NULL DEFAULT NULL,
    `authorization_code_metadata`   blob,
    `access_token_value`            blob,
    `access_token_issued_at`        timestamp NULL DEFAULT NULL,
    `access_token_expires_at`       timestamp NULL DEFAULT NULL,
    `access_token_metadata`         blob,
    `access_token_type`             varchar(100)  DEFAULT NULL,
    `access_token_scopes`           varchar(1000) DEFAULT NULL,
    `oidc_id_token_value`           blob,
    `oidc_id_token_issued_at`       timestamp NULL DEFAULT NULL,
    `oidc_id_token_expires_at`      timestamp NULL DEFAULT NULL,
    `oidc_id_token_metadata`        blob,
    `refresh_token_value`           blob,
    `refresh_token_issued_at`       timestamp NULL DEFAULT NULL,
    `refresh_token_expires_at`      timestamp NULL DEFAULT NULL,
    `refresh_token_metadata`        blob,
    `user_code_value`               blob,
    `user_code_issued_at`           timestamp NULL DEFAULT NULL,
    `user_code_expires_at`          timestamp NULL DEFAULT NULL,
    `user_code_metadata`            blob,
    `device_code_value`             blob,
    `device_code_issued_at`         timestamp NULL DEFAULT NULL,
    `device_code_expires_at`        timestamp NULL DEFAULT NULL,
    `device_code_metadata`          blob,
    PRIMARY KEY (`id`)
);
